function [fitresult, gof] = Average_Fidelity_WG_Ph_Regression(n_m, N_m, F_av,plotting)
%CRAverage_Fidelity_WG_Ph_RegressionEATEFIT(N_M,N_M,D)
%  Create a fit for the average Fidelity F_av depending n the number of
%  Waveguides N_m and the number of photons n_m via 2 double polynomial
%
%  Data for 'untitled fit 1' fit:
%      X Input : n_m
%      Y Input : N_m
%      Z Output: d
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 05-Aug-2019 10:08:55
if nargin<4
    plotting=0;
end

%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( n_m, N_m, F_av );

% Set up fittype and options.
ft = fittype( 'poly22' );
opts = fitoptions( 'Method', 'LinearLeastSquares' );
opts.Robust = 'LAR';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, opts );

% Plot fit with data.
    if plotting==1
    figure( 'Name', 'untitled fit 1' );
    h = plot( fitresult, [xData, yData], zData );
    legend( h, 'untitled fit 1', 'd vs. n_m, N_m', 'Location', 'NorthEast' );
    % Label axes
    xlabel n_m
    ylabel N_m
    zlabel d
    grid on
    view( 311.3, 45.2 );
end
end

